import "./globals.css";
import { Urbanist } from "next/font/google";
import { WindSong } from "next/font/google";
import { cx } from "@/utils";
import Header from "@/components/Header";

const urbanist = Urbanist({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-base",
});
const windsong = WindSong({
  subsets: ["latin"],
  variable: "--font-accent",
  weight: "400",
});

export const metadata = {
  title: "Val Journaling",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cx(
          urbanist.variable,
          windsong.variable,
          `font-base font-thin bg-light dark:bg-dark`
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
